namespace: djinn
driver:
  type: qemu
  image: arch
sources:
- https://github.com/djinn-ci/docs
stages:
- deps
- lint
- build
jobs:
- stage: deps
  commands:
  - pacman -S --noconfirm python python-jinja python-sphinx
  - sudo -u nobody yay -S --noconfirm python-sphinx-lint
- stage: lint
  commands:
  - cd docs
  - make lint
- stage: build
  commands:
  - cd docs
  - make html -b dirhtml
  - cd build/dirhtml
  - tar -czf docs.djinn-ci.com.tar.gz admin api index.html _static tutorial user
  artifacts:
  - docs/build/dirhtml/docs.djinn-ci.com.tar.gz
