site_name: Djinn CI Docs
site_url: https://docs.djinn-ci.com
repo_url: https://github.com/djinn-ci/docs
markdown_extensions:
- md_in_html
plugins:
- jinja2:
    exec: ["env.py"]
    macros: "templates/macros.html"
- minify:
    minify_html: true
    minify_css: true
nav:
- Home: "README.md"
- Tutorial: "tutorial.md"
- User:
  - Overview: "user/README.md"
  - Builds: "user/builds.md"
  - Namespaces: "user/namespaces.md"
  - Repos: "user/repos.md"
  - Cron: "user/cron.md"
  - Drivers: "user/drivers.md"
  - Manifest: "user/manifest.md"
  - Images: "user/images.md"
  - Objects: "user/objects.md"
  - Keys: "user/keys.md"
  - Variables: "user/variables.md"
  - Webhooks: "user/webhooks.md"
  - Offline Runner: "user/offline-runner.md"
- API:
  - Overview: "api/README.md"
  - OAuth: "api/oauth.md"
  - Builds: "api/builds.md"
  - Cron: "api/cron.md"
  - Images: "api/images.md"
  - Invites: "api/invites.md"
  - Keys: "api/keys.md"
  - Namespaces: "api/namespaces.md"
  - Objects: "api/objects.md"
  - User: "api/user.md"
  - Variables: "api/variables.md"
- Admin:
  - Overview: "admin/README.md"
  - Building: "admin/building.md"
  - Configuration: "admin/configuration.md"
  - Consumer: "admin/consumer.md"
  - Curator: "admin/curator.md"
  - Scheduler: "admin/scheduler.md"
  - Server: "admin/server.md"
  - Worker: "admin/worker.md"
theme:
  name: null
  custom_dir: theme
  locale: en
