

(function() {
	var els = document.querySelectorAll("[data-accordion]");
	var tab = {};

	for (var i = 0; i < els.length; i++) {
		var target = els[i].dataset.accordion;
		tab[target] = document.querySelector("[data-accordion-body="+target+"]");
	}

	for (var i = 0; i < els.length; i++) {
		els[i].addEventListener("click", function(e) {
			e.preventDefault();

			if (this.dataset.accordion in tab) {
				var el = tab[this.dataset.accordion];

				el.hidden = !el.hidden;


				if (el.hidden) {
					this.innerHTML = '<!-- Generated by IcoMoon.io --> <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M18.984 12.984h-6v6h-1.969v-6h-6v-1.969h6v-6h1.969v6h6v1.969z"></path></svg>';
				} else {
					this.innerHTML = '<!-- Generated by IcoMoon.io --> <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M18.984 6.422l-5.578 5.578 5.578 5.578-1.406 1.406-5.578-5.578-5.578 5.578-1.406-1.406 5.578-5.578-5.578-5.578 1.406-1.406 5.578 5.578 5.578-5.578z"></path></svg>';
				}
			}
		});
	}
})();

(function() {
	function span(text) {
		var span = document.createElement("span");
		span.textContent = text;
		return span;
	}

	var els = document.querySelectorAll("[data-copy]");
	var tab = {};

	for (var i = 0; i < els.length; i++) {
		var target = els[i].dataset.copy;
		tab[target] = document.querySelector("[data-copy-content="+target+"]");
	}

	for (var i = 0; i < els.length; i++) {
		els[i].addEventListener("click", function(e) {
			e.preventDefault();

			var root = this;
			var orig = root.innerHTML;

			var el = tab[this.dataset.copy];

			navigator.clipboard.writeText(el.textContent).then(function() {
				root.innerHTML = "Copied";
				root.classList.add("copy-alert");

				setTimeout(function() {
					root.innerHTML = orig;
					root.classList.remove("copy-alert");
				}, 1000);
			}, function() {
				root.innerHTML = "Failed to copy";
				root.classList.add("copy-alert");

				setTimeout(function() {
					root.innerHTML = orig;
					root.classList.remove("copy-alert");
				}, 1000);
			});
		});
	}
})();

(function() {
	var doc = document.querySelector(".doc");

	var toggle = document.querySelector("[data-nav-toggle]");
	var nav = document.querySelector("#" + toggle.dataset.navToggle);

	var active = nav.querySelector(".active");
	var curr = active.parentNode.previousElementSibling;

	var title = "";

	while (true) {
		if (curr == null) {
			break;
		}

		if (curr.classList.contains("nav-header")) {
			title = curr.innerText + " / ";
			break;
		}
		curr = curr.previousElementSibling;
	}

	document.querySelector("#nav-title").innerText = title + active.innerText;

	toggle.addEventListener("click", function(e) {
		e.preventDefault();

		nav.hidden = !nav.hidden;
	});

	doc.addEventListener("click", function(e) {
		if ( ! nav.hidden) {
			nav.hidden = true;
		}
	});
})();
